// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceState } from "./DeviceState";

export type AgentStatus = { state: DeviceState, current_video_id: string | null, position_secs: number | null, duration_secs: number | null, };
