// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceState } from "./DeviceState";

export type Device = { id: string, name: string, ip: string, state: DeviceState, current_video: string | null, last_seen: number, };
