// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Video = { id: string, filename: string, duration_secs: number | null, size_bytes: bigint, };
